name: Backend Tests
on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.1

      - name: Install dependencies
        run: |
          cd back/
          npm ci

      - name: Run Tests
        run: |
          cd back/                 
          npm test

      - name: Test Report
        uses: phoenix-actions/test-reporting@v9
        id: test-report
        if: success() || failure()
        with:
          name: JUnit Tests
          path: reports/junit-*.xml
          reporter: jest-junit