name: Backend Tests
on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        working-directory: back
        run: mvn -B compile --file pom.xml

      - name: Run Tests
        working-directory: back
        run: mvn surefire:test

      - name: Test Report Generation
        uses: phoenix-actions/test-reporting@v9
        id: test-report
        if: success() || failure()
        with:
          name: JUnit Tests
          path: back/target/site/surefire-reports/*.xml
          reporter: java-junit