name: Backend Tests
on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        working-directory: back
        id: build-job
        run: mvn -B compile --file pom.xml

      - run: "echo "### :white_check_mark: Build Passed" >> $GITHUB_STEP_SUMMARY"
        if: jobs.build-job.result == 'success'

      - run: "echo "### :x: Build Failed" >> $GITHUB_STEP_SUMMARY"
        if: jobs.build-job.result == 'failure'

      - name: Run Tests
        working-directory: back
        run: mvn -B test --file pom.xml

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/TEST-*.xml"
        if: success() || failure()

    #   - name: Test Report Generation
    #     uses: phoenix-actions/test-reporting@v9
    #     id: test-report
    #     if: success() || failure()
    #     with:
    #       name: JUnit Tests
    #       path: back/target/surefire-reports/*.xml
    #       reporter: java-junit