name: Builds & Tests
on:
  pull_request:
  push:
jobs:
  backend-build-test:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build
        working-directory: back
        run: mvn -B compile --file pom.xml

      - name: Run Tests
        working-directory: back
        run: mvn -B test --file pom.xml

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/TEST-*.xml"
        if: success() || failure()

      - name: Coverage Summary
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: 'back/target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Backend test coverage result'
          coverage_report_name: 'Backend test coverage result'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  frontend-build-test:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run Tests
        working-directory: front
        run: npm test -- --browsers=ChromeHeadless --watch=false --code-coverage

      - name: Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: front/coverage/bobapp/cobertura-coverage.xml
          badge: true
          format: markdown
          indicators: true
          output: both
